#### Project 1 
#### Ahmad Megdadi

### Part A

In [1]:
#importing important libraries 

import pandas as pd
import numpy as np

###### getting Data from the source about concrete dataset

In [2]:
concrete_data = pd.read_csv('https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv')
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

###### using all columns as predictors and the last one as a target which is the results

In [3]:
concrete_data_columns = concrete_data.columns

predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
target = concrete_data['Strength'] # Strength column

### Part B

In [4]:
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [ ]:
import keras

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [ ]:
# build the model
model = regression_model()

In [ ]:
# fit the model
model.fit(predictors_norm, target, validation_split=0.3, epochs=50, verbose=2)

In [ ]:
list_mse = []

for i in range(50):
    X_train, X_test, y_train, y_test = train_test_split(predictors, target, shuffle= True, random_state=50, test_size= 0.3)
    train_model = linear_nn()
    train_model.fit(X_train, y_train, epochs= 50, verbose= 2)
    test_predict = train_model.predict(X_test)
    mse = mean_squared_error(y_test, test_predict)
    list_mse.append(mse)

In [ ]:
std_mse = np.std(list_mse)
mean_mse =np.mean(list_mse)

print('Mean of MSE: {}'.format(mean_mse))
print('Standard Deviation of MSE: {}'.format(std_mse))

#### i don't have keras on my pc so i have worked with the labs that IBM provided and then copied the results here

Train on 721 samples, validate on 309 samples
Epoch 1/50
 - 2s - loss: 1661.0664 - val_loss: 1202.0987
Epoch 2/50
 - 1s - loss: 1640.9966 - val_loss: 1189.8484
Epoch 3/50
 - 1s - loss: 1620.8383 - val_loss: 1177.8417
Epoch 4/50
 - 1s - loss: 1600.4900 - val_loss: 1165.7220
Epoch 5/50
 - 1s - loss: 1579.8657 - val_loss: 1153.4397
Epoch 6/50
 - 1s - loss: 1558.8185 - val_loss: 1140.6967
Epoch 7/50
 - 1s - loss: 1536.6379 - val_loss: 1127.5472
Epoch 8/50
 - 1s - loss: 1514.0529 - val_loss: 1113.5491
Epoch 9/50
 - 1s - loss: 1489.6670 - val_loss: 1099.2602
Epoch 10/50
 - 1s - loss: 1464.4699 - val_loss: 1083.5979
Epoch 11/50
 - 0s - loss: 1437.2405 - val_loss: 1067.3464
Epoch 12/50
 - 1s - loss: 1408.7014 - val_loss: 1050.2770
Epoch 13/50
 - 1s - loss: 1378.7963 - val_loss: 1031.8011
Epoch 14/50
 - 1s - loss: 1347.1655 - val_loss: 1013.1278
Epoch 15/50
 - 1s - loss: 1313.9834 - val_loss: 993.2131
Epoch 16/50
 - 1s - loss: 1280.1123 - val_loss: 972.3778
Epoch 17/50
 - 1s - loss: 1244.3310 - val_loss: 951.4169
Epoch 18/50
 - 1s - loss: 1207.8718 - val_loss: 929.3188
Epoch 19/50
 - 1s - loss: 1170.8487 - val_loss: 906.7831
Epoch 20/50
 - 0s - loss: 1132.5433 - val_loss: 884.4143
Epoch 21/50
 - 1s - loss: 1093.8224 - val_loss: 861.4874
Epoch 22/50
 - 1s - loss: 1055.2877 - val_loss: 838.0821
Epoch 23/50
 - 1s - loss: 1016.0838 - val_loss: 814.1512
Epoch 24/50
 - 1s - loss: 977.3020 - val_loss: 790.2998
Epoch 25/50
 - 1s - loss: 938.4114 - val_loss: 766.8536
Epoch 26/50
 - 1s - loss: 900.4840 - val_loss: 743.3209
Epoch 27/50
 - 1s - loss: 863.0425 - val_loss: 719.7636
Epoch 28/50
 - 1s - loss: 826.0339 - val_loss: 696.4621
Epoch 29/50
 - 1s - loss: 790.3694 - val_loss: 673.1305
Epoch 30/50
 - 1s - loss: 754.8022 - val_loss: 650.3118
Epoch 31/50
 - 1s - loss: 720.8709 - val_loss: 627.8150
Epoch 32/50
 - 1s - loss: 687.8293 - val_loss: 605.3999
Epoch 33/50
 - 1s - loss: 656.2537 - val_loss: 584.0977
Epoch 34/50
 - 0s - loss: 625.9809 - val_loss: 563.2518
Epoch 35/50
 - 1s - loss: 597.1188 - val_loss: 542.8689
Epoch 36/50
 - 1s - loss: 569.3407 - val_loss: 523.2802
Epoch 37/50
 - 0s - loss: 543.4774 - val_loss: 504.1764
Epoch 38/50
 - 1s - loss: 518.3697 - val_loss: 485.5717
Epoch 39/50
 - 1s - loss: 495.5443 - val_loss: 467.6628
Epoch 40/50
 - 1s - loss: 473.2520 - val_loss: 450.1939
Epoch 41/50
 - 1s - loss: 453.0236 - val_loss: 433.8684
Epoch 42/50
 - 1s - loss: 433.4414 - val_loss: 418.8517
Epoch 43/50
 - 1s - loss: 416.0267 - val_loss: 403.1017
Epoch 44/50
 - 1s - loss: 398.9385 - val_loss: 388.7239
Epoch 45/50
 - 0s - loss: 383.7135 - val_loss: 374.5776
Epoch 46/50
 - 0s - loss: 368.6660 - val_loss: 361.4704
Epoch 47/50
 - 1s - loss: 355.3687 - val_loss: 349.2885
Epoch 48/50
 - 1s - loss: 343.1016 - val_loss: 337.4762
Epoch 49/50
 - 0s - loss: 331.6919 - val_loss: 325.8671
Epoch 50/50
 - 1s - loss: 321.2359 - val_loss: 315.3604

### Part C

In [ ]:
# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

# build the model
model = regression_model()

#100 epochs
model.fit(predictors_norm, target, validation_split=0.3, epochs=100, verbose=2)

std_mse = np.std(list_mse)
mean_mse =np.mean(list_mse)

print('Mean of MSE: {}'.format(mean_mse))
print('Standard Deviation of MSE: {}'.format(std_mse))

### Part D

In [ ]:
# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model.add(Dense(10, activation='relu'))
    model.add(Dense(10, activation='relu'))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

# build the model
model = regression_model()

model.fit(predictors_norm, target, validation_split=0.3, epochs=50, verbose=2)

std_mse = np.std(list_mse)
mean_mse =np.mean(list_mse)

print('Mean of MSE: {}'.format(mean_mse))
print('Standard Deviation of MSE: {}'.format(std_mse))